#pragma once

#include <map>
#include <vector>
#include <unordered_set>

#include <llvm/IR/InstVisitor.h>

#include "CatDataDependencies.hpp"
#include "CatFunction.hpp"
#include "llvm/Support/raw_ostream.h"

using MAP_TYPE = std::map<llvm::Value*, std::unordered_set<llvm::Instruction*>>;

/**
 * Visitor class that generates GEN and KILL sets for each
 * llvm::Instruction. Must run after CatInstructionVisitor and must
 * have called setMappedInstructions() and setValueModifications()
 * before calling visit(). No checks are done to ensure these
 * preconditions are met.
 */
class CatGenKillVisitor : public llvm::InstVisitor<CatGenKillVisitor> {

    const std::vector<llvm::Instruction*>* mappedInstructions_;
    const MAP_TYPE* valueModificationMap_;

    // GEN and KILL sets are stored here
    std::map<llvm::Instruction*, CatDataDependencies> genKillMap_;

    /**
     * Gets the llvm::Value that is modified by a given CAT function.
     *
     * @param func CAT function to analyze
     * @param callInst Call instruction representing the CAT function
     * @return The llvm::Value that is modified by the CAT function, or nullptr if the instruction doesn't modify anything
     */
    llvm::Value* getModifiedValue(const CatFunction* func, llvm::CallInst& callInst);

    public:

        /**
         * Constructor.
         */
        CatGenKillVisitor() : mappedInstructions_(nullptr), valueModificationMap_(nullptr), genKillMap_() {}

        /**
         * Called for each instruction. Will generate GEN and KILL sets
         * for the instructions.
         */
        void visitInstruction(llvm::Instruction& inst);

        /**
         * Sets the mapped instructions list generated by the CatInstructionVisitor.
         *
         * @param mappedInstructions The list of all instructions in this function that we will generate GEN and KILL sets for.
         */
        void setMappedInstructions(const std::vector<llvm::Instruction*>& mappedInstructions) {
            mappedInstructions_ = &mappedInstructions;
        }

        /**
         * Sets the value modification map generated by the CatInstructionVisitor.
         *
         * @param valueModificationMap Map from modified values to all instructions that modify them.
         */
        void setValueModifications(const MAP_TYPE& valueModificationMap) {
            valueModificationMap_ = &valueModificationMap;
        }

        /**
         * Gets the generated GEN/KILL sets for each instruction.
         */
        const auto& getGenKillMap() {
            return genKillMap_;
        }

        /**
         * Prints GEN/KILL sets in the H1 format.
         */
        void print();
};
