#pragma once

#include <vector>
#include <map>
#include <unordered_set>

#include <llvm/IR/Function.h>
#include <llvm/ADT/SmallBitVector.h>

#include "CatDataDependencies.hpp"

using MAP_TYPE = std::map<llvm::Value*, std::unordered_set<llvm::CallInst*>>;

class CatInOutProcessor {

    const std::vector<llvm::CallInst*>* callInstructions_;
    const MAP_TYPE* valueModificationMap_;
    std::map<llvm::Instruction*, CatDataDependencies>* dataDepsMap_;
    std::map<llvm::BasicBlock*, CatDataDependencies> bbDataDepsMap_;

    bool changesHappened_;

    void processBasicBlock(llvm::BasicBlock& bb);
    llvm::CallInst* processInstruction(llvm::Instruction& inst, llvm::CallInst* prevInst);

    public:

        /**
         * Constructor.
         */
        CatInOutProcessor() : callInstructions_(nullptr), valueModificationMap_(nullptr), dataDepsMap_(nullptr), bbDataDepsMap_(), changesHappened_(false) {}

        /**
         * Sets the call instructions list generated by the CatCallInstVisitor.
         *
         * @param callInstructions The list of all call instructions in this function.
         */
        void setCallInstructions(const std::vector<llvm::CallInst*>& callInstructions) {
            callInstructions_ = &callInstructions;
        }

        /**
         * Sets the value modification map generated by the CatCallInstVisitor.
         *
         * @param valueModificationMap Map from modified values to all instructions that modify them.
         */
        void setValueModifications(const MAP_TYPE& valueModificationMap) {
            valueModificationMap_ = &valueModificationMap;
        }

        void setDataDepsMap(std::map<llvm::Instruction*, CatDataDependencies>& dataDepsMap) {
            dataDepsMap_ = &dataDepsMap;
        }

        bool changesHappened() {
            return changesHappened_;
        }

        void processOnce(llvm::Function& func);
};
