name: C/C++ CI

on:
  push:
    branches:
      - master

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Install dependencies
        run: sudo apt update -m && sudo apt install cmake clang-12 libllvm12 llvm-12-dev
        shell: bash
      - name: Run CMake
        run: cd "${{ github.workspace }}/../../_temp" && cmake -G "Unix Makefiles" "${{ github.workspace }}"
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Install dependencies
        run: sudo apt update -m && sudo apt install cmake doxygen clang-12 libllvm12 llvm-12-dev
        shell: bash
      - name: Run CMake
        run: cd "${{ github.workspace }}/../../_temp" && cmake -G "Unix Makefiles" "${{ github.workspace }}"
      - name: Generate docs
        run: cd "${{ github.workspace }}/../../_temp" && make doxygen
      - name: Upload docs
        uses: actions/upload-artifact@v1
        with:
          name: Doxygen_Docs
          path: "${{ github.workspace }}/../../_temp/html"
